export const SALESORDER_LOADING = "SALESORDER_LOADING";
export const SALESORDER_SUCCESS = "SALESORDER_SUCCESS";
export const SALESORDER_FAILED = "SALESORDER_FAILED";
export const LOADCUSTOMERS_FAILED = "LOADCUSTOMERS_FAILED";
export const LOADCUSTOMERS_LOADING = "LOADCUSTOMERS_LOADING";
export const LOADCUSTOMERS_SUCCESS = "LOADCUSTOMERS_SUCCESS";