export const Product_Model = {
    PRODUCTID: '',
    PRODUCTNAME: '',
    PRODUCT_DESCRIPTION: '',
    PRODUCT_TYPE: '',
    THUMBNAIL_URL: '',
    IMAGE_URL:'',
    PRODUCT_STARTTIME:'',
    PRODUCT_ENDTIME:'',
    TAG:'',
    STOREID:'',
    product_attribute_id:'',
    CATEGORY:'',
    PRICE:'',
    DISCOUNTED_PRICE:'',
    IS_RECOMMENDED:'',
    IS_POPULAR:'',
    IS_NEW:'',
    VEG_NONVEG:'',
    TAX_RATE:'',
    COMMISSION_RATE:'',
    IS_ACTIVE:''
    }